# Generated by Django 3.0.2 on 2020-01-15 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0005_approvals_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvals',
            name='grade',
        ),
    ]
